"""empty message

Revision ID: 001
Revises:
Create Date: 2019-12-13 17:50:04.591442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "playlist",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(datetime())"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_playlist_created_at"), "playlist", ["created_at"], unique=False
    )
    op.create_table(
        "item",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(datetime())"),
            nullable=False,
        ),
        sa.Column("artist", sa.String(length=255), nullable=True),
        sa.Column("duration", sa.Integer(), nullable=True),
        sa.Column(
            "played", sa.Boolean(), server_default=sa.text("(FALSE)"), nullable=True
        ),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("url", sa.String(length=255), nullable=True),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("playlist_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["playlist_id"], ["playlist.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("url"),
    )
    op.create_index(op.f("ix_item_created_at"), "item", ["created_at"], unique=False)
    op.create_index(op.f("ix_item_playlist_id"), "item", ["playlist_id"], unique=False)
    op.create_index(op.f("ix_item_user_id"), "item", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_item_user_id"), table_name="item")
    op.drop_index(op.f("ix_item_playlist_id"), table_name="item")
    op.drop_index(op.f("ix_item_created_at"), table_name="item")
    op.drop_table("item")
    op.drop_index(op.f("ix_playlist_created_at"), table_name="playlist")
    op.drop_table("playlist")
    # ### end Alembic commands ###
