"""add Item.user_id

Revision ID: 002
Revises: 001
Create Date: 2019-11-18 23:28:43.716102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '002'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('user_id', sa.String(length=36), nullable=False, server_default=''))
    op.create_index(op.f('ix_item_created_at'), 'item', ['created_at'], unique=False)
    op.create_index(op.f('ix_item_user_id'), 'item', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_user_id'), table_name='item')
    op.drop_index(op.f('ix_item_created_at'), table_name='item')
    op.drop_column('item', 'user_id')
    # ### end Alembic commands ###
